-- MySQL Script generated by MySQL Workbench
-- Sun Dec  8 17:18:06 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Course` (
  `course_enrollment` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`course_enrollment`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Person` (
  `person_enrollment` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `cpf` CHAR(13) NOT NULL,
  `telephone` VARCHAR(11) NULL DEFAULT NULL,
  PRIMARY KEY (`person_enrollment`));


-- -----------------------------------------------------
-- Table `mydb`.`Teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Teacher` (
  `teacher_enrollment` INT(11) NOT NULL,
  `admission_date` DATE NOT NULL,
  PRIMARY KEY (`teacher_enrollment`),
  CONSTRAINT `teacher_enrollment_teacher_fk`
    FOREIGN KEY (`teacher_enrollment`)
    REFERENCES `mydb`.`Person` (`person_enrollment`));


-- -----------------------------------------------------
-- Table `mydb`.`Discipline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Discipline` (
  `disc_code` INT(11) NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(100) NOT NULL,
  `teacher_enrollment` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`disc_code`),
  INDEX `disc_code_teacher_fk` (`teacher_enrollment` ASC) VISIBLE,
  CONSTRAINT `disc_code_teacher_fk`
    FOREIGN KEY (`teacher_enrollment`)
    REFERENCES `mydb`.`Teacher` (`teacher_enrollment`));


-- -----------------------------------------------------
-- Table `mydb`.`Class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Class` (
  `disc_code` INT(11) NULL DEFAULT NULL,
  `course_enrollment` INT(11) NULL DEFAULT NULL,
  `semester` VARCHAR(6) NULL DEFAULT NULL,
  `classroom_number` VARCHAR(4) NOT NULL,
  `shift` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`disc_code`, `course_enrollment`, `semester`),
  INDEX `class_course_enrollment_fk` (`course_enrollment` ASC) VISIBLE,
  CONSTRAINT `class_codigo_disciplina_fk`
    FOREIGN KEY (`disc_code`)
    REFERENCES `mydb`.`Discipline` (`disc_code`),
  CONSTRAINT `class_course_enrollment_fk`
    FOREIGN KEY (`course_enrollment`)
    REFERENCES `mydb`.`Course` (`course_enrollment`));


-- -----------------------------------------------------
-- Table `mydb`.`Minister`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Minister` (
  `disc_code` INT(11) NULL DEFAULT NULL,
  `course_enrollment` INT(11) NULL DEFAULT NULL,
  `semester` VARCHAR(6) NULL DEFAULT NULL,
  `teacher_enrollment` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`disc_code`, `course_enrollment`, `semester`, `teacher_enrollment`),
  INDEX `minister_enrollment_teacher_fk` (`teacher_enrollment` ASC) VISIBLE,
  CONSTRAINT `minister_class_fk`
    FOREIGN KEY (`disc_code` , `course_enrollment` , `semester`)
    REFERENCES `mydb`.`Class` (`disc_code` , `course_enrollment` , `semester`),
  CONSTRAINT `minister_enrollment_teacher_fk`
    FOREIGN KEY (`teacher_enrollment`)
    REFERENCES `mydb`.`Teacher` (`teacher_enrollment`));


-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `student_enrollment` INT(11) NULL DEFAULT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`student_enrollment`),
  CONSTRAINT `student_student_enrollment_fk`
    FOREIGN KEY (`student_enrollment`)
    REFERENCES `mydb`.`Person` (`person_enrollment`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student_class` (
  `disc_code` INT(11) NULL DEFAULT NULL,
  `course_enrollment` INT(11) NULL DEFAULT NULL,
  `semester` VARCHAR(6) NULL DEFAULT NULL,
  `student_enrollment` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`disc_code`, `course_enrollment`, `semester`, `student_enrollment`),
  INDEX `student_class_student_enrollment_fk` (`student_enrollment` ASC) VISIBLE,
  CONSTRAINT `student_class_class_fk`
    FOREIGN KEY (`disc_code` , `course_enrollment` , `semester`)
    REFERENCES `mydb`.`Class` (`disc_code` , `course_enrollment` , `semester`),
  CONSTRAINT `student_class_student_enrollment_fk`
    FOREIGN KEY (`student_enrollment`)
    REFERENCES `mydb`.`Student` (`student_enrollment`));


-- -----------------------------------------------------
-- Table `mydb`.`Student_course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student_course` (
  `student_student_enrollment` INT(11) NOT NULL,
  `course_course_enrollment` INT(11) NOT NULL,
  PRIMARY KEY (`student_student_enrollment`, `course_course_enrollment`),
  INDEX `fk_course_student_course1_idx` (`course_course_enrollment` ASC) VISIBLE,
  CONSTRAINT `fk_course_student_student1`
    FOREIGN KEY (`student_student_enrollment`)
    REFERENCES `mydb`.`Student` (`student_enrollment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_course_student_course1`
    FOREIGN KEY (`course_course_enrollment`)
    REFERENCES `mydb`.`Course` (`course_enrollment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
