-- MySQL Script generated by MySQL Workbench
-- Mon Dec  9 17:06:03 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Course` (
  `course_enrollment` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`course_enrollment`),
  UNIQUE INDEX `course_enrollment_UNIQUE` (`course_enrollment` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `telephone` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  UNIQUE INDEX `person_enrollment_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------
------------------------------------------
-- Table `mydb`.`Teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Teacher` (
  `teacher_enrollment` INT NOT NULL,
  `admission_date` DATE NOT NULL,
  PRIMARY KEY (`teacher_enrollment`),
  UNIQUE INDEX `teacher_enrollment_UNIQUE` (`teacher_enrollment` ASC),
  CONSTRAINT `teacher_enrollment_teacher_fk`
    FOREIGN KEY (`teacher_enrollment`)
    REFERENCES `mydb`.`Person` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Discipline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Discipline` (
  `disc_code` INT(11) NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(100) NOT NULL,
  `teacher_enrollment` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`disc_code`),
  INDEX `disc_code_teacher_fk` (`teacher_enrollment` ASC),
  CONSTRAINT `disc_code_teacher_fk`
    FOREIGN KEY (`teacher_enrollment`)
    REFERENCES `mydb`.`Teacher` (`teacher_enrollment`));


-- -----------------------------------------------------
-- Table `mydb`.`Class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Class` (
  `class_code` INT(11) NOT NULL AUTO_INCREMENT,
  `disc_code` INT(11) NOT NULL,
  `course_enrollment` INT NOT NULL,
  `semester` VARCHAR(6) NOT NULL,
  `classroom_number` VARCHAR(4) NOT NULL,
  `shift` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`class_code`, `disc_code`, `course_enrollment`),
  INDEX `class_course_enrollment_fk` (`course_enrollment` ASC),
  UNIQUE INDEX `class_code_UNIQUE` (`class_code` ASC),
  INDEX `class_codigo_disciplina_fk` (`disc_code` ASC),
  CONSTRAINT `class_codigo_disciplina_fk`
    FOREIGN KEY (`disc_code`)
    REFERENCES `mydb`.`Discipline` (`disc_code`),
  CONSTRAINT `class_course_enrollment_fk`
    FOREIGN KEY (`course_enrollment`)
    REFERENCES `mydb`.`Course` (`course_enrollment`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Minister`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Minister` (
  `minister_code` INT NOT NULL AUTO_INCREMENT,
  `class_code` INT(11) NOT NULL,
  `teacher_enrollment` INT NOT NULL,
  PRIMARY KEY (`minister_code`, `class_code`, `teacher_enrollment`),
  INDEX `minister_enrollment_teacher_fk` (`teacher_enrollment` ASC),
  INDEX `minister_class_fk` (`class_code` ASC),
  CONSTRAINT `minister_class_fk`
    FOREIGN KEY (`class_code`)
    REFERENCES `mydb`.`Class` (`class_code`),
  CONSTRAINT `minister_enrollment_teacher_fk`
    FOREIGN KEY (`teacher_enrollment`)
    REFERENCES `mydb`.`Teacher` (`teacher_enrollment`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `student_enrollment` INT NOT NULL,
  `status_on` TINYINT NOT NULL,
  `enr_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`student_enrollment`),
  UNIQUE INDEX `student_enrollment_UNIQUE` (`student_enrollment` ASC),
  CONSTRAINT `student_student_enrollment_fk`
    FOREIGN KEY (`student_enrollment`)
    REFERENCES `mydb`.`Person` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student_class` (
  `st_class_code` INT(11) NOT NULL AUTO_INCREMENT,
  `class_code` INT(11) NOT NULL,
  `student_enrollment` INT NOT NULL,
  PRIMARY KEY (`st_class_code`, `class_code`, `student_enrollment`),
  INDEX `student_class_student_enrollment_fk` (`student_enrollment` ASC),
  UNIQUE INDEX `st_class_code_UNIQUE` (`st_class_code` ASC),
  INDEX `student_class_class_fk` (`class_code` ASC) ,
  CONSTRAINT `student_class_class_fk`
    FOREIGN KEY (`class_code`)
    REFERENCES `mydb`.`Class` (`disc_code`),
  CONSTRAINT `student_class_student_enrollment_fk`
    FOREIGN KEY (`student_enrollment`)
    REFERENCES `mydb`.`Student` (`student_enrollment`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student_course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student_course` (
  `student_course_code` INT NOT NULL AUTO_INCREMENT,
  `student_enrollment` INT NOT NULL,
  `course_enrollment` INT NOT NULL,
  PRIMARY KEY (`student_course_code`, `student_enrollment`, `course_enrollment`),
  INDEX `fk_course_student_course1_idx` (`course_enrollment` ASC),
  INDEX `fk_course_student_student1` (`student_enrollment` ASC),
  CONSTRAINT `fk_course_student_student1`
    FOREIGN KEY (`student_enrollment`)
    REFERENCES `mydb`.`Student` (`student_enrollment`),
  CONSTRAINT `fk_course_student_course1`
    FOREIGN KEY (`course_enrollment`)
    REFERENCES `mydb`.`Course` (`course_enrollment`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

insert into person (name,cpf,telephone) values
( 'Alice', '11224308493', '81998912935'),
('Elizabeth', '11224208491', '81998912935');

insert into student (student_enrollment,status_on) values
(1, true);
